# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test StudentsApp

on:
  push:
    branches: [ "main" ] # Triggers the workflow on push to the main branch
  pull_request:
    branches: [ "main" ] # Triggers the workflow on pull requests to the main branch
  workflow_dispatch: # Allows manual triggering of the workflow

jobs: # Define the jobs that will run in this workflow
  build_and_test: # Build and Test Job
    name: Build and Test                  # This is the name of the job that will run
    runs-on: ubuntu-latest                # The job will run on the latest version of Ubuntu
    steps:                                # Define the steps that will be executed in this job
    - name: Checkout Repo                 # Checkout the repository code or switch to a specific branch
      uses: actions/checkout@v4           # This action checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it
    - name: Use Node.js 22.x              # Set up Node.js environment
      uses: actions/setup-node@v4         # This action sets up a Node.js environment for use in the workflow
      with:                               # Specify the Node.js version to use
        node-version: 22.x                # Use the latest version of Node.js 22.x
    - name: Build (Install dependencies)  # Install dependencies
      run: npm ci                         # This command installs the dependencies defined in package-lock.json, ensuring a clean and reproducible build
    - name: Run Integration tests         # Run integration tests
      run: npm test                       # This command runs the tests defined in the project, typically using a testing framework like Jest or Mocha
    
    # More steps can be added here as needed, such as linting, building the project, or deploying it
    # - name: Run security scan # Run security scan (test for vulnerabilities)
    #   run: npm audit # This command checks for vulnerabilities in the dependencies and reports any issues found at or above the specified severity level (high in this case)
  
  # Additional job for security tests - running in parallel with build_and_test
  # security_tests: # the same as build_and_test, but only runs the security scan
  #   name: Security Tests 
  #   # needs: build_and_test # This job depends on the build_and_test job, meaning it will only run after that job has completed successfully
  #   runs-on: ubuntu-latest 
  #   steps: 
  #   - name: Checkout Repo 
  #     uses: actions/checkout@v4 
  #   - name: Use Node.js 22.x 
  #     uses: actions/setup-node@v4 
  #     with: 
  #       node-version: 22.x 
  #   - name: Build (Install dependencies) 
  #     run: npm ci 
  #   - name: Run security scan 
  #     run: npm audit 
 